---
# tasks file for deploy_container
- name: Ensure Docker-py installed
  pip: name=docker-py state=latest

- name: Pull Container
  docker_image:
    name: "{{ docker_registry | ends_in_slash }}{{ container_name }}"
    tag: "{{ container_tag }}"

- name: Start Container
  docker_container:
    name: "{{ application_name }}"
    image: "{{ docker_registry | ends_in_slash }}{{container_name}}:{{container_tag}}"
    log_driver: "{{ log_driver | default(omit) }}"
    labels: "{{ container_labels | default(omit) }}"
    network_mode: "{{ container_network_mode | default('bridge') }}"
    volumes: "{{ container_volumes | default(omit) }}"
    command: "{{ container_command | default(omit) }}"
    env: "{{ container_env | default(omit) }}"
    state: started
    restart: yes
    published_ports: all