---
# tasks file for deploy_container
- name: Ensure Docker-py installed
  pip: name=docker-py state=latest

- name: Pull Container
  docker_image:
    name: "{{ item.docker_registry | ends_in_slash }}{{ item.container_name }}"
    tag: "{{ item.container_tag }}"
  with_items: "{{ containers }}"

- name: Container Action
  docker_container:
    name: "{{ item.application_name }}"
    image: "{{ item.docker_registry | ends_in_slash }}{{item.container_name}}:{{item.container_tag}}"
    log_driver: "{{ item.log_driver | default(omit) }}"
    labels: "{{ item.container_labels | default(omit) }}"
    network_mode: "{{ item.container_network_mode | default('bridge') }}"
    volumes: "{{ item.container_volumes | default(omit) }}"
    command: "{{ item.container_command | default(omit) }}"
    env: "{{ item.container_env | default(omit) }}"
    state: "{{ item.container_state | default('started') }}"
    restart: "{{ item.container_restart | default('no') }}"
    published_ports: "{{ item.publish_ports | default('all') }}"
  with_items: "{{ containers }}"